insert into csc_role (role_id, role_name, role_description)
values (CSC_ROLE_SEQUENCE.nextval,'Faculty','Faculty');

insert into csc_role (role_id, role_name, role_description)
values (CSC_ROLE_SEQUENCE.nextval,'Student','Student');

insert into csc_role (role_id, role_name, role_description)
values (CSC_ROLE_SEQUENCE.nextval,'Teaching Assistant','Teaching Assistant');

insert into csc_role (role_id, role_name, role_description)
values (CSC_ROLE_SEQUENCE.nextval,'Admin','Admin');

insert into csc_user (user_id,user_id_char,USER_FNAME,USER_LNAME,USER_EMAIL,USER_PASSWORD)
values (CSC_USER_SEQUENCE .nextval,'tregan','Tom','Regan','tregan@ncsu.edu','tregan');

insert into csc_user (user_id,user_id_char,USER_FNAME,USER_LNAME,USER_EMAIL,USER_PASSWORD)
values (CSC_USER_SEQUENCE .nextval,'jmick','Jenelle','Mick','jmick@ncsu.edu','jmick');

insert into csc_user (user_id,user_id_char,USER_FNAME,USER_LNAME,USER_EMAIL,USER_PASSWORD)
values (CSC_USER_SEQUENCE .nextval,'mfiser','Michal','Fiser','mfiser@ncsu.edu','mfiser');


insert into csc_user (user_id,user_id_char,USER_FNAME,USER_LNAME,USER_EMAIL,USER_PASSWORD)
values (CSC_USER_SEQUENCE .nextval,'jander','Joseph','Anderson','jander@ncsu.edu','jander');


insert into csc_user (user_id,user_id_char,USER_FNAME,USER_LNAME,USER_EMAIL,USER_PASSWORD)
values (CSC_USER_SEQUENCE .nextval,'jHarla','Jitendra','Harlalka','jHarla@ncsu.edu','jHarla');

insert into csc_user (user_id,user_id_char,USER_FNAME,USER_LNAME,USER_EMAIL,USER_PASSWORD)
values (CSC_USER_SEQUENCE .nextval,'aneela','Aishwarya','Neelakantan','aneela@ncsu.edu','aneela');

insert into csc_user (user_id,user_id_char,USER_FNAME,USER_LNAME,USER_EMAIL,USER_PASSWORD)
values (CSC_USER_SEQUENCE .nextval,'mjones','Mary','Jones','mjones@ncsu.edu','mjones');

insert into csc_user (user_id,user_id_char,USER_FNAME,USER_LNAME,USER_EMAIL,USER_PASSWORD)
values (CSC_USER_SEQUENCE .nextval,'jmoyer','James','Moyer','jmoyer@ncsu.edu','jmoyer');

insert into csc_user (user_id,user_id_char,USER_FNAME,USER_LNAME,USER_EMAIL,USER_PASSWORD)
values (CSC_USER_SEQUENCE .nextval,'kogan','Kemafor','Ogan','kogan@ncsu.edu','kogan');

insert into csc_user (user_id,user_id_char,USER_FNAME,USER_LNAME,USER_EMAIL,USER_PASSWORD)
values (CSC_USER_SEQUENCE .nextval,'rchirkova','Rada','Chirkova','rchirkova@ncsu.edu','rchirkova');

insert into csc_user (user_id,user_id_char,USER_FNAME,USER_LNAME,USER_EMAIL,USER_PASSWORD)
values (CSC_USER_SEQUENCE .nextval,'chealey','Cristopher','Healey','chealey@ncsu.edu','chealey');

Insert into csc_course (CSC_COURSE_COURSE_ID,CSC_COURSE_COURSE_NAME,CSC_COURSE_STARTDATE,CSC_COURSE_ENDDATE,
CSC_COURSE_MAX_ENROLL_NO,CSC_COURSE_NUMBER_OF_STUDENTS,CSC_COURSE_COURSE_ID_CHAR,CSC_COURSE_TOKEN)
values (CSC_COURSE_SEQUENCE.nextval,'Database Systems',to_date('2014/08/27','YYYY/MM/DD'),to_date('2014/12/12','YYYY/MM/DD'),
5,3,'CSC440','CSC440FALL14');

Insert into csc_course (CSC_COURSE_COURSE_ID,CSC_COURSE_COURSE_NAME,CSC_COURSE_STARTDATE,CSC_COURSE_ENDDATE,
CSC_COURSE_MAX_ENROLL_NO,CSC_COURSE_NUMBER_OF_STUDENTS,CSC_COURSE_COURSE_ID_CHAR,CSC_COURSE_TOKEN)
values (CSC_COURSE_SEQUENCE.nextval,'Database Systems',to_date('2014/08/25','YYYY/MM/DD'),to_date('2014/12/10','YYYY/MM/DD'),
5,3,'CSC540','CSC540FALL14');

Insert into csc_course (CSC_COURSE_COURSE_ID,CSC_COURSE_COURSE_NAME,CSC_COURSE_STARTDATE,CSC_COURSE_ENDDATE,
CSC_COURSE_MAX_ENROLL_NO,CSC_COURSE_NUMBER_OF_STUDENTS,CSC_COURSE_COURSE_ID_CHAR,CSC_COURSE_TOKEN)
values (CSC_COURSE_SEQUENCE.nextval,'Advanced Data Structures',to_date('2013/08/25','YYYY/MM/DD'),to_date('2013/12/06','YYYY/MM/DD'),
5,3,'CSC541','CSC541FALL14');

insert into CSC_LEVEL_STUDENT (CSC_LEVEL_STUDENT_LEVEL_ID ,CSC_LEVEL_LEVEL_TYPE)
values (CSC_LEVEL_STUDENT_SEQUENCE.nextval,'Under Graduate');

insert into CSC_LEVEL_STUDENT (CSC_LEVEL_STUDENT_LEVEL_ID ,CSC_LEVEL_LEVEL_TYPE)
values (CSC_LEVEL_STUDENT_SEQUENCE.nextval,'Graduate');

Insert into CSC_LEVEL_STUDENT_USER (CSC_LEVEL_STU_USER_SURR_KEY,CSC_LEVEL_STU_USER_LEVEL_ID,CSC_LEVEL_STU_USER_USER_ID)
values (CSC_STUDENT_LEVEL_SEQUENCE.nextval,1,1);

Insert into CSC_LEVEL_STUDENT_USER (CSC_LEVEL_STU_USER_SURR_KEY,CSC_LEVEL_STU_USER_LEVEL_ID,CSC_LEVEL_STU_USER_USER_ID)
values (CSC_STUDENT_LEVEL_SEQUENCE.nextval,2,2);

Insert into CSC_LEVEL_STUDENT_USER (CSC_LEVEL_STU_USER_SURR_KEY,CSC_LEVEL_STU_USER_LEVEL_ID,CSC_LEVEL_STU_USER_USER_ID)
values (CSC_STUDENT_LEVEL_SEQUENCE.nextval,1,3);

Insert into CSC_LEVEL_STUDENT_USER (CSC_LEVEL_STU_USER_SURR_KEY,CSC_LEVEL_STU_USER_LEVEL_ID,CSC_LEVEL_STU_USER_USER_ID)
values (CSC_STUDENT_LEVEL_SEQUENCE.nextval,1,4);

Insert into CSC_LEVEL_STUDENT_USER (CSC_LEVEL_STU_USER_SURR_KEY,CSC_LEVEL_STU_USER_LEVEL_ID,CSC_LEVEL_STU_USER_USER_ID)
values (CSC_STUDENT_LEVEL_SEQUENCE.nextval,2,5);

Insert into CSC_LEVEL_STUDENT_USER (CSC_LEVEL_STU_USER_SURR_KEY,CSC_LEVEL_STU_USER_LEVEL_ID,CSC_LEVEL_STU_USER_USER_ID)
values (CSC_STUDENT_LEVEL_SEQUENCE.nextval,2,6);

Insert into CSC_LEVEL_STUDENT_USER (CSC_LEVEL_STU_USER_SURR_KEY,CSC_LEVEL_STU_USER_LEVEL_ID,CSC_LEVEL_STU_USER_USER_ID)
values (CSC_STUDENT_LEVEL_SEQUENCE.nextval,2,7);

Insert into CSC_LEVEL_STUDENT_USER (CSC_LEVEL_STU_USER_SURR_KEY,CSC_LEVEL_STU_USER_LEVEL_ID,CSC_LEVEL_STU_USER_USER_ID)
values (CSC_STUDENT_LEVEL_SEQUENCE.nextval,2,8);

insert into CSC_CLASS (CSC_CLASS_SURR_KEY,CSC_CLASS_CLASS_ID,CSC_CLASS_COURSE_ID)
values (CSC_CLASS_SEQUENCE.nextval, 1,1);

insert into CSC_CLASS (CSC_CLASS_SURR_KEY,CSC_CLASS_CLASS_ID,CSC_CLASS_COURSE_ID)
values (CSC_CLASS_SEQUENCE.nextval, 1,2);

insert into CSC_CLASS (CSC_CLASS_SURR_KEY,CSC_CLASS_CLASS_ID,CSC_CLASS_COURSE_ID)
values (CSC_CLASS_SEQUENCE.nextval, 1,3);

insert into CSC_USER_ROLE(USER_ROLE_USER_ID,USER_ROLE_ROLE_ID,CSC_U_R_CLASS_SURR_KEY)
values (10,1,1);

insert into CSC_USER_ROLE(USER_ROLE_USER_ID,USER_ROLE_ROLE_ID,CSC_U_R_CLASS_SURR_KEY)
values (6,3,1);

insert into CSC_USER_ROLE(USER_ROLE_USER_ID,USER_ROLE_ROLE_ID,CSC_U_R_CLASS_SURR_KEY)
values (2,3,1);

insert into CSC_USER_ROLE(USER_ROLE_USER_ID,USER_ROLE_ROLE_ID,CSC_U_R_CLASS_SURR_KEY)
values (1,2,1);

insert into CSC_USER_ROLE(USER_ROLE_USER_ID,USER_ROLE_ROLE_ID,CSC_U_R_CLASS_SURR_KEY)
values (3,2,1);

insert into CSC_USER_ROLE(USER_ROLE_USER_ID,USER_ROLE_ROLE_ID,CSC_U_R_CLASS_SURR_KEY)
values (4,2,1);

insert into CSC_USER_ROLE(USER_ROLE_USER_ID,USER_ROLE_ROLE_ID,CSC_U_R_CLASS_SURR_KEY)
values (9,1,2);

insert into CSC_USER_ROLE(USER_ROLE_USER_ID,USER_ROLE_ROLE_ID,CSC_U_R_CLASS_SURR_KEY)
values (5,3,2);

insert into CSC_USER_ROLE(USER_ROLE_USER_ID,USER_ROLE_ROLE_ID,CSC_U_R_CLASS_SURR_KEY)
values (6,2,2);

insert into CSC_USER_ROLE(USER_ROLE_USER_ID,USER_ROLE_ROLE_ID,CSC_U_R_CLASS_SURR_KEY)
values (2,2,2);

insert into CSC_USER_ROLE(USER_ROLE_USER_ID,USER_ROLE_ROLE_ID,CSC_U_R_CLASS_SURR_KEY)
values (7,2,2);

insert into CSC_USER_ROLE(USER_ROLE_USER_ID,USER_ROLE_ROLE_ID,CSC_U_R_CLASS_SURR_KEY)
values (11,1,3);

insert into CSC_USER_ROLE(USER_ROLE_USER_ID,USER_ROLE_ROLE_ID,CSC_U_R_CLASS_SURR_KEY)
values (8,3,3);

insert into CSC_USER_ROLE(USER_ROLE_USER_ID,USER_ROLE_ROLE_ID,CSC_U_R_CLASS_SURR_KEY)
values (6,2,3);

insert into CSC_USER_ROLE(USER_ROLE_USER_ID,USER_ROLE_ROLE_ID,CSC_U_R_CLASS_SURR_KEY)
values (7,2,3);

insert into CSC_USER_ROLE(USER_ROLE_USER_ID,USER_ROLE_ROLE_ID,CSC_U_R_CLASS_SURR_KEY)
values (2,2,3);

insert into CSC_SCORINGTYPE(SCORINGTYPE_ID,SCORINGTYPE_DESCRIPTION)
values (CSC_SCORINGTYPE_SEQUENCE.nextval,'Latest Attempt');

insert into CSC_SCORINGTYPE(SCORINGTYPE_ID,SCORINGTYPE_DESCRIPTION)
values (CSC_SCORINGTYPE_SEQUENCE.nextval,'Maximum Score');

insert into CSC_SCORINGTYPE(SCORINGTYPE_ID,SCORINGTYPE_DESCRIPTION)
values (CSC_SCORINGTYPE_SEQUENCE.nextval,'Average Score');

Insert into CSC_TEXTBOOK (CSC_TEXTBOOK_ISBN,CSC_TEXTBOOK_TITLE,CSC_TEXTBOOK_AUTHOR)
values ('0072465638','Database Management Systems (3rd edition)','Raghu Ramakrishnan and Johannes Gehrke');

Insert into CSC_CHAPTER (CSC_CHAPTER_CHAPTER_SURR_KEY,CSC_CHAPTER_CHAPTER_ID,CSC_CHAPTER_TITLE,CSC_CHAPTER_ISBN)
values (CSC_CHAPTER_SEQUENCE.nextval,1,'Introduction to Database Design','0072465638');

Insert into CSC_CHAPTER (CSC_CHAPTER_CHAPTER_SURR_KEY,CSC_CHAPTER_CHAPTER_ID,CSC_CHAPTER_TITLE,CSC_CHAPTER_ISBN)
values (CSC_CHAPTER_SEQUENCE.nextval,2,'SQL: Queries, Constraints, Triggers','0072465638');

Insert into CSC_CHAPTER (CSC_CHAPTER_CHAPTER_SURR_KEY,CSC_CHAPTER_CHAPTER_ID,CSC_CHAPTER_TITLE,CSC_CHAPTER_ISBN)
values (CSC_CHAPTER_SEQUENCE.nextval,3,'Storing data: Disks and Files','0072465638');

Insert into CSC_SECTION(CSC_SECTION_SECTION_SURR_KEY,CSC_SECTION_SECTION_ID,CSC_SECTION_SUPER_SECTION_ID,
CSC_SECTION_TITLE,CSC_SECTION_CONTENT,CSC_SECTION_CHAPTER_SURR_KEY)
values (CSC_SECTION_SEQUENCE.nextval,1,NULL,'Database design and ER diagram',NULL ,1);

Insert into CSC_SECTION(CSC_SECTION_SECTION_SURR_KEY,CSC_SECTION_SECTION_ID,CSC_SECTION_SUPER_SECTION_ID,
CSC_SECTION_TITLE,CSC_SECTION_CONTENT,CSC_SECTION_CHAPTER_SURR_KEY)
values (CSC_SECTION_SEQUENCE.nextval,2,NULL,'Additional Features of ER Model',NULL ,1);

Insert into CSC_SECTION(CSC_SECTION_SECTION_SURR_KEY,CSC_SECTION_SECTION_ID,CSC_SECTION_SUPER_SECTION_ID,
CSC_SECTION_TITLE,CSC_SECTION_CONTENT,CSC_SECTION_CHAPTER_SURR_KEY)
values (CSC_SECTION_SEQUENCE.nextval,1,2,'Key Constraints',NULL ,1);

Insert into CSC_SECTION(CSC_SECTION_SECTION_SURR_KEY,CSC_SECTION_SECTION_ID,CSC_SECTION_SUPER_SECTION_ID,
CSC_SECTION_TITLE,CSC_SECTION_CONTENT,CSC_SECTION_CHAPTER_SURR_KEY)
values (CSC_SECTION_SEQUENCE.nextval,2,2,'Participant constraints',NULL ,1);

Insert into CSC_SECTION(CSC_SECTION_SECTION_SURR_KEY,CSC_SECTION_SECTION_ID,CSC_SECTION_SUPER_SECTION_ID,
CSC_SECTION_TITLE,CSC_SECTION_CONTENT,CSC_SECTION_CHAPTER_SURR_KEY)
values (CSC_SECTION_SEQUENCE.nextval,1,NULL ,'Union, Intersect and Except',NULL ,2);

Insert into CSC_SECTION(CSC_SECTION_SECTION_SURR_KEY,CSC_SECTION_SECTION_ID,CSC_SECTION_SUPER_SECTION_ID,
CSC_SECTION_TITLE,CSC_SECTION_CONTENT,CSC_SECTION_CHAPTER_SURR_KEY)
values (CSC_SECTION_SEQUENCE.nextval,2,NULL ,'Aggregate Operators',NULL ,2);

Insert into CSC_SECTION(CSC_SECTION_SECTION_SURR_KEY,CSC_SECTION_SECTION_ID,CSC_SECTION_SUPER_SECTION_ID,
CSC_SECTION_TITLE,CSC_SECTION_CONTENT,CSC_SECTION_CHAPTER_SURR_KEY)
values (CSC_SECTION_SEQUENCE.nextval,1,2 ,'Group by and Having clause',NULL ,2);

Insert into CSC_SECTION(CSC_SECTION_SECTION_SURR_KEY,CSC_SECTION_SECTION_ID,CSC_SECTION_SUPER_SECTION_ID,
CSC_SECTION_TITLE,CSC_SECTION_CONTENT,CSC_SECTION_CHAPTER_SURR_KEY)
values (CSC_SECTION_SEQUENCE.nextval,1,NULL ,'The Memory Hierarchy',NULL ,3);

Insert into CSC_SECTION(CSC_SECTION_SECTION_SURR_KEY,CSC_SECTION_SECTION_ID,CSC_SECTION_SUPER_SECTION_ID,
CSC_SECTION_TITLE,CSC_SECTION_CONTENT,CSC_SECTION_CHAPTER_SURR_KEY)
values (CSC_SECTION_SEQUENCE.nextval,1,1 ,'Magnetic disks',NULL ,3);

Insert into CSC_SECTION(CSC_SECTION_SECTION_SURR_KEY,CSC_SECTION_SECTION_ID,CSC_SECTION_SUPER_SECTION_ID,
CSC_SECTION_TITLE,CSC_SECTION_CONTENT,CSC_SECTION_CHAPTER_SURR_KEY)
values (CSC_SECTION_SEQUENCE.nextval,2,NULL ,'Redundant Arrays of Independent disks',NULL ,3);

Insert into CSC_SECTION(CSC_SECTION_SECTION_SURR_KEY,CSC_SECTION_SECTION_ID,CSC_SECTION_SUPER_SECTION_ID,
CSC_SECTION_TITLE,CSC_SECTION_CONTENT,CSC_SECTION_CHAPTER_SURR_KEY)
values (CSC_SECTION_SEQUENCE.nextval,1,2 ,'Data striping',NULL ,3);

Insert into CSC_SECTION(CSC_SECTION_SECTION_SURR_KEY,CSC_SECTION_SECTION_ID,CSC_SECTION_SUPER_SECTION_ID,
CSC_SECTION_TITLE,CSC_SECTION_CONTENT,CSC_SECTION_CHAPTER_SURR_KEY)
values (CSC_SECTION_SEQUENCE.nextval,2,2 ,'Redundancy',NULL ,3);

Insert into CSC_TEXTBOOK (CSC_TEXTBOOK_ISBN,CSC_TEXTBOOK_TITLE,CSC_TEXTBOOK_AUTHOR)
values ('0471605212','File Organization and Processing','Alan L. Tharp');

Insert into CSC_CHAPTER (CSC_CHAPTER_CHAPTER_SURR_KEY,CSC_CHAPTER_CHAPTER_ID,CSC_CHAPTER_TITLE,CSC_CHAPTER_ISBN)
values (CSC_CHAPTER_SEQUENCE.nextval,1,'Primary File Organiztions','0471605212');

Insert into CSC_CHAPTER (CSC_CHAPTER_CHAPTER_SURR_KEY,CSC_CHAPTER_CHAPTER_ID,CSC_CHAPTER_TITLE,CSC_CHAPTER_ISBN)
values (CSC_CHAPTER_SEQUENCE.nextval,2,'Tree Structures','0471605212');

Insert into CSC_SECTION(CSC_SECTION_SECTION_SURR_KEY,CSC_SECTION_SECTION_ID,CSC_SECTION_SUPER_SECTION_ID,
CSC_SECTION_TITLE,CSC_SECTION_CONTENT,CSC_SECTION_CHAPTER_SURR_KEY)
values (CSC_SECTION_SEQUENCE.nextval,1,NULL,'Sequential file organizations',NULL ,4);

Insert into CSC_SECTION(CSC_SECTION_SECTION_SURR_KEY,CSC_SECTION_SECTION_ID,CSC_SECTION_SUPER_SECTION_ID,
CSC_SECTION_TITLE,CSC_SECTION_CONTENT,CSC_SECTION_CHAPTER_SURR_KEY)
values (CSC_SECTION_SEQUENCE.nextval,1,1,'Bianry search',NULL ,4);

Insert into CSC_SECTION(CSC_SECTION_SECTION_SURR_KEY,CSC_SECTION_SECTION_ID,CSC_SECTION_SUPER_SECTION_ID,
CSC_SECTION_TITLE,CSC_SECTION_CONTENT,CSC_SECTION_CHAPTER_SURR_KEY)
values (CSC_SECTION_SEQUENCE.nextval,2,1,'Interpolation search',NULL ,4);

Insert into CSC_SECTION(CSC_SECTION_SECTION_SURR_KEY,CSC_SECTION_SECTION_ID,CSC_SECTION_SUPER_SECTION_ID,
CSC_SECTION_TITLE,CSC_SECTION_CONTENT,CSC_SECTION_CHAPTER_SURR_KEY)
values (CSC_SECTION_SEQUENCE.nextval,2,NULL,'Direct file organization',NULL ,4);

Insert into CSC_SECTION(CSC_SECTION_SECTION_SURR_KEY,CSC_SECTION_SECTION_ID,CSC_SECTION_SUPER_SECTION_ID,
CSC_SECTION_TITLE,CSC_SECTION_CONTENT,CSC_SECTION_CHAPTER_SURR_KEY)
values (CSC_SECTION_SEQUENCE.nextval,1,2 ,'Hahsing functions',NULL ,4);

Insert into CSC_SECTION(CSC_SECTION_SECTION_SURR_KEY,CSC_SECTION_SECTION_ID,CSC_SECTION_SUPER_SECTION_ID,
CSC_SECTION_TITLE,CSC_SECTION_CONTENT,CSC_SECTION_CHAPTER_SURR_KEY)
values (CSC_SECTION_SEQUENCE.nextval,1,NULL ,'Binary tree structures',NULL ,5);

Insert into CSC_SECTION(CSC_SECTION_SECTION_SURR_KEY,CSC_SECTION_SECTION_ID,CSC_SECTION_SUPER_SECTION_ID,
CSC_SECTION_TITLE,CSC_SECTION_CONTENT,CSC_SECTION_CHAPTER_SURR_KEY)
values (CSC_SECTION_SEQUENCE.nextval,1,1 ,'AVL Trees',NULL ,5);

Insert into CSC_SECTION(CSC_SECTION_SECTION_SURR_KEY,CSC_SECTION_SECTION_ID,CSC_SECTION_SUPER_SECTION_ID,
CSC_SECTION_TITLE,CSC_SECTION_CONTENT,CSC_SECTION_CHAPTER_SURR_KEY)
values (CSC_SECTION_SEQUENCE.nextval,2,NULL ,'Hashing techniques',NULL ,5);

Insert into CSC_SECTION(CSC_SECTION_SECTION_SURR_KEY,CSC_SECTION_SECTION_ID,CSC_SECTION_SUPER_SECTION_ID,
CSC_SECTION_TITLE,CSC_SECTION_CONTENT,CSC_SECTION_CHAPTER_SURR_KEY)
values (CSC_SECTION_SEQUENCE.nextval,1,2 ,'Extendible hashing',NULL ,5);

Update CSC_SECTION
SET CSC_SECTION_SUPER_SECTION_ID = 6
where CSC_SECTION_SECTION_SURR_KEY = 7;

Update CSC_SECTION
SET CSC_SECTION_SUPER_SECTION_ID = 8
where CSC_SECTION_SECTION_SURR_KEY = 9;

Update CSC_SECTION
SET CSC_SECTION_SUPER_SECTION_ID = 10
where CSC_SECTION_SECTION_SURR_KEY = 11;

Update CSC_SECTION
SET CSC_SECTION_SUPER_SECTION_ID = 10
where CSC_SECTION_SECTION_SURR_KEY = 12;

Update CSC_SECTION
SET CSC_SECTION_SUPER_SECTION_ID = 13
where CSC_SECTION_SECTION_SURR_KEY = 14;

Update CSC_SECTION
SET CSC_SECTION_SUPER_SECTION_ID = 13
where CSC_SECTION_SECTION_SURR_KEY = 15;

Update CSC_SECTION
SET CSC_SECTION_SUPER_SECTION_ID = 16
where CSC_SECTION_SECTION_SURR_KEY = 17;

Update CSC_SECTION
SET CSC_SECTION_SUPER_SECTION_ID = 18
where CSC_SECTION_SECTION_SURR_KEY = 19;

Update CSC_SECTION
SET CSC_SECTION_SUPER_SECTION_ID = 20
where CSC_SECTION_SECTION_SURR_KEY = 21;

Insert into CSC_COURSE_TEXTBOOK (CSC_COURSE_TEXTBOOK_SURR_KEY,CSC_CRS_TXTBK_CSC_CRS_CRS_ID,CSC_CRS_TXTBK_CSC_TXTBK_ISBN)
values (CSC_COURSE_TEXTBOOK_SEQUENCE.nextval,1,'0072465638');

Insert into CSC_COURSE_TEXTBOOK (CSC_COURSE_TEXTBOOK_SURR_KEY,CSC_CRS_TXTBK_CSC_CRS_CRS_ID,CSC_CRS_TXTBK_CSC_TXTBK_ISBN)
values (CSC_COURSE_TEXTBOOK_SEQUENCE.nextval,2,'0072465638');

Insert into CSC_COURSE_TEXTBOOK (CSC_COURSE_TEXTBOOK_SURR_KEY,CSC_CRS_TXTBK_CSC_CRS_CRS_ID,CSC_CRS_TXTBK_CSC_TXTBK_ISBN)
values (CSC_COURSE_TEXTBOOK_SEQUENCE.nextval,2,'0471605212');

Insert into CSC_COURSE_TEXTBOOK (CSC_COURSE_TEXTBOOK_SURR_KEY,CSC_CRS_TXTBK_CSC_CRS_CRS_ID,CSC_CRS_TXTBK_CSC_TXTBK_ISBN)
values (CSC_COURSE_TEXTBOOK_SEQUENCE.nextval,3,'0471605212');

Insert into CSC_LEVEL(CSC_LEVEL_LEVEL_ID,CSC_LEVEL_LEVEL_TYPE) values (CSC_LEVEL_SEQUENCE.nextval,'UnderGraduate');

Insert into CSC_LEVEL(CSC_LEVEL_LEVEL_ID,CSC_LEVEL_LEVEL_TYPE) values (CSC_LEVEL_SEQUENCE.nextval,'Graduate');

Insert into CSC_COURSE_LEVEL(CSC_COURSE_LEVEL_SURR_KEY,CSC_COURSE_LEVEL_LEVEL_ID,CSC_COURSE_LEVEL_COURSE_ID)
values (CSC_COURSE_LEVEL_SEQUENCE.nextval,1,1);

Insert into CSC_COURSE_LEVEL(CSC_COURSE_LEVEL_SURR_KEY,CSC_COURSE_LEVEL_LEVEL_ID,CSC_COURSE_LEVEL_COURSE_ID)
values (CSC_COURSE_LEVEL_SEQUENCE.nextval,2,2);

Insert into CSC_COURSE_LEVEL(CSC_COURSE_LEVEL_SURR_KEY,CSC_COURSE_LEVEL_LEVEL_ID,CSC_COURSE_LEVEL_COURSE_ID)
values (CSC_COURSE_LEVEL_SEQUENCE.nextval,2,3);

Insert into CSC_TOPIC(TOPIC_ID ,TOPIC_KEYWORD)
values (CSC_TOPIC_SEQUENCE.nextval,'Introduction to database design');

Insert into CSC_TOPIC(TOPIC_ID ,TOPIC_KEYWORD)
values (CSC_TOPIC_SEQUENCE.nextval,'SQL: Queries, Constraints, Triggers');

Insert into CSC_TOPIC(TOPIC_ID ,TOPIC_KEYWORD)
values (CSC_TOPIC_SEQUENCE.nextval,'Storing data: Disks and Files');

Insert into CSC_TOPIC(TOPIC_ID ,TOPIC_KEYWORD)
values (CSC_TOPIC_SEQUENCE.nextval,'Primary File organizations');

Insert into CSC_TOPIC(TOPIC_ID ,TOPIC_KEYWORD)
values (CSC_TOPIC_SEQUENCE.nextval,'Tree Structures');

Insert into CSC_COURSE_TOPIC(CSC_COURSE_TOPIC_SURR_KEY,CSC_COURSE_TOPIC_TOPIC_ID,CSC_COURSE_TOPIC_COURSE_ID)
values (CSC_COURSE_TOPIC_SEQUENCE.nextval,1,1);

Insert into CSC_COURSE_TOPIC(CSC_COURSE_TOPIC_SURR_KEY,CSC_COURSE_TOPIC_TOPIC_ID,CSC_COURSE_TOPIC_COURSE_ID)
values (CSC_COURSE_TOPIC_SEQUENCE.nextval,2,1);

Insert into CSC_COURSE_TOPIC(CSC_COURSE_TOPIC_SURR_KEY,CSC_COURSE_TOPIC_TOPIC_ID,CSC_COURSE_TOPIC_COURSE_ID)
values (CSC_COURSE_TOPIC_SEQUENCE.nextval,1,2);

Insert into CSC_COURSE_TOPIC(CSC_COURSE_TOPIC_SURR_KEY,CSC_COURSE_TOPIC_TOPIC_ID,CSC_COURSE_TOPIC_COURSE_ID)
values (CSC_COURSE_TOPIC_SEQUENCE.nextval,3,2);

Insert into CSC_COURSE_TOPIC(CSC_COURSE_TOPIC_SURR_KEY,CSC_COURSE_TOPIC_TOPIC_ID,CSC_COURSE_TOPIC_COURSE_ID)
values (CSC_COURSE_TOPIC_SEQUENCE.nextval,4,2);

Insert into CSC_COURSE_TOPIC(CSC_COURSE_TOPIC_SURR_KEY,CSC_COURSE_TOPIC_TOPIC_ID,CSC_COURSE_TOPIC_COURSE_ID)
values (CSC_COURSE_TOPIC_SEQUENCE.nextval,5,2);

Insert into CSC_COURSE_TOPIC(CSC_COURSE_TOPIC_SURR_KEY,CSC_COURSE_TOPIC_TOPIC_ID,CSC_COURSE_TOPIC_COURSE_ID)
values (CSC_COURSE_TOPIC_SEQUENCE.nextval,4,3);

Insert into CSC_COURSE_TOPIC(CSC_COURSE_TOPIC_SURR_KEY,CSC_COURSE_TOPIC_TOPIC_ID,CSC_COURSE_TOPIC_COURSE_ID)
values (CSC_COURSE_TOPIC_SEQUENCE.nextval,5,3);

Insert into CSC_CHAPTER_TOPIC(CSC_CHAPTER_TOPIC_SURR_KEY,CSC_CHAPTER_TOPIC_TOPIC_ID,CSC_CHAPTER_TOPIC_CHP_SURR_KEY)
values(CSC_CHAPTER_TOPIC_SEQUENCE.nextval,1,1);

Insert into CSC_CHAPTER_TOPIC(CSC_CHAPTER_TOPIC_SURR_KEY,CSC_CHAPTER_TOPIC_TOPIC_ID,CSC_CHAPTER_TOPIC_CHP_SURR_KEY)
values(CSC_CHAPTER_TOPIC_SEQUENCE.nextval,2,2);

Insert into CSC_CHAPTER_TOPIC(CSC_CHAPTER_TOPIC_SURR_KEY,CSC_CHAPTER_TOPIC_TOPIC_ID,CSC_CHAPTER_TOPIC_CHP_SURR_KEY)
values(CSC_CHAPTER_TOPIC_SEQUENCE.nextval,3,3);

Insert into CSC_CHAPTER_TOPIC(CSC_CHAPTER_TOPIC_SURR_KEY,CSC_CHAPTER_TOPIC_TOPIC_ID,CSC_CHAPTER_TOPIC_CHP_SURR_KEY)
values(CSC_CHAPTER_TOPIC_SEQUENCE.nextval,4,4);

Insert into CSC_CHAPTER_TOPIC(CSC_CHAPTER_TOPIC_SURR_KEY,CSC_CHAPTER_TOPIC_TOPIC_ID,CSC_CHAPTER_TOPIC_CHP_SURR_KEY)
values(CSC_CHAPTER_TOPIC_SEQUENCE.nextval,5,5);

Insert into csc_exercise 
(EXERCISE_ID,EXERCISE_NAME,EXERCISE_STARTDATE,EXERCISE_ENDDATE,EXERCISE_DIFFICULTY_RANGE1,EXERCISE_DIFFICULTY_RANGE2,
EXERCISE_RETRYLIMIT,EXERCISE_CORRECTPT,EXERCISE_PENALTYPT,EXERCISE_SCORINGTYPE,EXERCISE_COURSE)
values (CSC_EXERCISE_SEQUENCE.nextval,'EXERCISE FOR CSC 540',to_date('08-12-2014','MM-DD-
YYYY'),to_date('09-19-2014','MM-DD-YYYY'),1,3,2,3,1,1,2);

Insert into csc_exercise 
(EXERCISE_ID,EXERCISE_NAME,EXERCISE_STARTDATE,EXERCISE_ENDDATE,EXERCISE_DIFFICULTY_RANGE1,EXERCISE_DIFFICULTY_RANGE2,
EXERCISE_RETRYLIMIT,EXERCISE_CORRECTPT,EXERCISE_PENALTYPT,EXERCISE_SCORINGTYPE,EXERCISE_COURSE)
values (CSC_EXERCISE_SEQUENCE.nextval,'EXERCISE FOR CSC 540',to_date('09-21-2014','MM-DD-
YYYY'),to_date('10-10-2014','MM-DD-YYYY'),3,5,-1,4,1,3,2);

insert into CSC_EXERCISE_TOPIC (CSC_EXERCISE_TOPIC_SURR_KEY,CSC_EXERCISE_TOPIC_TOPIC_ID,CSC_EXERCISE_TOPIC_EXERCISE_ID)
values (CSC_EXERCISE_TOPIC_SEQUENCE.nextval,1,1);

insert into CSC_EXERCISE_TOPIC (CSC_EXERCISE_TOPIC_SURR_KEY,CSC_EXERCISE_TOPIC_TOPIC_ID,CSC_EXERCISE_TOPIC_EXERCISE_ID)
values (CSC_EXERCISE_TOPIC_SEQUENCE.nextval,3,2);

INSERT INTO CSC_QUESTIONBANK(QUESTIONBANK_ID,QUESTIONBANK_TEXT,QUESTIONBANK_HINT,QUESTIONBANK_EXPLANATION,
QUESTIONBANK_DIFFICULTYLEVEL,CSC_QB_IS_PARAMETERIZED)
VALUES (CSC_QUESTIONBANK_SEQUENCE.nextval,'Question 1?','Hint text Q1','detailed explanation Q1',2,'F');

INSERT INTO CSC_QUESTIONBANK(QUESTIONBANK_ID,QUESTIONBANK_TEXT,QUESTIONBANK_HINT,QUESTIONBANK_EXPLANATION,
QUESTIONBANK_DIFFICULTYLEVEL,CSC_QB_IS_PARAMETERIZED)
VALUES (CSC_QUESTIONBANK_SEQUENCE.nextval,'Question 2?','Hint text Q2','detailed explanation Q2',3,'F');

INSERT INTO CSC_QUESTIONBANK(QUESTIONBANK_ID,QUESTIONBANK_TEXT,QUESTIONBANK_HINT,QUESTIONBANK_EXPLANATION,
QUESTIONBANK_DIFFICULTYLEVEL,CSC_QB_IS_PARAMETERIZED)
VALUES (CSC_QUESTIONBANK_SEQUENCE.nextval,'Consider a disk with a <sector size>, <tracks per surface>, <sectors per track>, <double-sided
platters>, <average seek time>','Hint text Q3','detailed explanation Q3',2,'T');

UPDATE CSC_QUESTIONBANK
SET QUESTIONBANK_TEXT = 'Consider a disk with a <sector size>, <tracks per surface>, <sectors per track>, <double-sided
platters>, <average seek time>. What is the capacity of the track in bytes?'
where QUESTIONBANK_ID = 3;

UPDATE CSC_QUESTIONBANK
SET CSC_QUESTIONBANK_TOPIC_ID = 1
WHERE QUESTIONBANK_ID = 1;

UPDATE CSC_QUESTIONBANK
SET CSC_QUESTIONBANK_TOPIC_ID = 2
WHERE QUESTIONBANK_ID = 2;

INSERT INTO CSC_ANSWERBANK(ANSWERBANK_ID,ANSWERBANK_TEXT,ANSWERBANK_EXPLANATION)
VALUES (CSC_ANSWERBANK_SEQUENCE.NEXTVAL,'ans 1',NULL);

INSERT INTO CSC_ANSWERBANK(ANSWERBANK_ID,ANSWERBANK_TEXT,ANSWERBANK_EXPLANATION)
VALUES (CSC_ANSWERBANK_SEQUENCE.NEXTVAL,'ans 2',NULL);

INSERT INTO CSC_ANSWERBANK(ANSWERBANK_ID,ANSWERBANK_TEXT,ANSWERBANK_EXPLANATION)
VALUES (CSC_ANSWERBANK_SEQUENCE.NEXTVAL,'ans 3','short explanation 3');

INSERT INTO CSC_ANSWERBANK(ANSWERBANK_ID,ANSWERBANK_TEXT,ANSWERBANK_EXPLANATION)
VALUES (CSC_ANSWERBANK_SEQUENCE.NEXTVAL,'ans 4','short explanation 4');

INSERT INTO CSC_ANSWERBANK(ANSWERBANK_ID,ANSWERBANK_TEXT,ANSWERBANK_EXPLANATION)
VALUES (CSC_ANSWERBANK_SEQUENCE.NEXTVAL,'ans 5','short explanation 5');

INSERT INTO CSC_ANSWERBANK(ANSWERBANK_ID,ANSWERBANK_TEXT,ANSWERBANK_EXPLANATION)
VALUES (CSC_ANSWERBANK_SEQUENCE.NEXTVAL,'ans 6','short explanation 6');

INSERT INTO CSC_ANSWERBANK(ANSWERBANK_ID,ANSWERBANK_TEXT,ANSWERBANK_EXPLANATION)
VALUES (CSC_ANSWERBANK_SEQUENCE.NEXTVAL,'ans 3','NULL');

INSERT INTO CSC_ANSWERBANK(ANSWERBANK_ID,ANSWERBANK_TEXT,ANSWERBANK_EXPLANATION)
VALUES (CSC_ANSWERBANK_SEQUENCE.NEXTVAL,'ans 7','short explanation 7');

INSERT INTO CSC_ANSWERBANK(ANSWERBANK_ID,ANSWERBANK_TEXT,ANSWERBANK_EXPLANATION)
VALUES (CSC_ANSWERBANK_SEQUENCE.NEXTVAL,'ans 8','short explanation 8');

INSERT INTO CSC_ANSWERBANK(ANSWERBANK_ID,ANSWERBANK_TEXT,ANSWERBANK_EXPLANATION)
VALUES (CSC_ANSWERBANK_SEQUENCE.NEXTVAL,'ans 1v1',NULL);

INSERT INTO CSC_ANSWERBANK(ANSWERBANK_ID,ANSWERBANK_TEXT,ANSWERBANK_EXPLANATION)
VALUES (CSC_ANSWERBANK_SEQUENCE.NEXTVAL,'ans 2v1',NULL);

INSERT INTO CSC_ANSWERBANK(ANSWERBANK_ID,ANSWERBANK_TEXT,ANSWERBANK_EXPLANATION)
VALUES (CSC_ANSWERBANK_SEQUENCE.NEXTVAL,'ans 3v1',NULL);

INSERT INTO CSC_ANSWERBANK(ANSWERBANK_ID,ANSWERBANK_TEXT,ANSWERBANK_EXPLANATION)
VALUES (CSC_ANSWERBANK_SEQUENCE.NEXTVAL,'ans 4v1','short explanation 4');

INSERT INTO CSC_ANSWERBANK(ANSWERBANK_ID,ANSWERBANK_TEXT,ANSWERBANK_EXPLANATION)
VALUES (CSC_ANSWERBANK_SEQUENCE.NEXTVAL,'ans 5v1','short explanation 5');

INSERT INTO CSC_ANSWERBANK(ANSWERBANK_ID,ANSWERBANK_TEXT,ANSWERBANK_EXPLANATION)
VALUES (CSC_ANSWERBANK_SEQUENCE.NEXTVAL,'ans 6v1','short explanation 6');

INSERT INTO CSC_ANSWERBANK(ANSWERBANK_ID,ANSWERBANK_TEXT,ANSWERBANK_EXPLANATION)
VALUES (CSC_ANSWERBANK_SEQUENCE.NEXTVAL,'ans 7v1','short explanation 7');

INSERT INTO CSC_ANSWERBANK(ANSWERBANK_ID,ANSWERBANK_TEXT,ANSWERBANK_EXPLANATION)
VALUES (CSC_ANSWERBANK_SEQUENCE.NEXTVAL,'ans 8v1','short explanation 8');

INSERT INTO CSC_ANSWERBANK(ANSWERBANK_ID,ANSWERBANK_TEXT,ANSWERBANK_EXPLANATION)
VALUES (CSC_ANSWERBANK_SEQUENCE.NEXTVAL,'ans 1v2',NULL);

INSERT INTO CSC_ANSWERBANK(ANSWERBANK_ID,ANSWERBANK_TEXT,ANSWERBANK_EXPLANATION)
VALUES (CSC_ANSWERBANK_SEQUENCE.NEXTVAL,'ans 2v2',NULL);

INSERT INTO CSC_ANSWERBANK(ANSWERBANK_ID,ANSWERBANK_TEXT,ANSWERBANK_EXPLANATION)
VALUES (CSC_ANSWERBANK_SEQUENCE.NEXTVAL,'ans 3v2',NULL);

INSERT INTO CSC_ANSWERBANK(ANSWERBANK_ID,ANSWERBANK_TEXT,ANSWERBANK_EXPLANATION)
VALUES (CSC_ANSWERBANK_SEQUENCE.NEXTVAL,'ans 4v2','short explanation 4');

INSERT INTO CSC_ANSWERBANK(ANSWERBANK_ID,ANSWERBANK_TEXT,ANSWERBANK_EXPLANATION)
VALUES (CSC_ANSWERBANK_SEQUENCE.NEXTVAL,'ans 5v2','short explanation 5');

INSERT INTO CSC_ANSWERBANK(ANSWERBANK_ID,ANSWERBANK_TEXT,ANSWERBANK_EXPLANATION)
VALUES (CSC_ANSWERBANK_SEQUENCE.NEXTVAL,'ans 6v2','short explanation 6');

INSERT INTO CSC_ANSWERBANK(ANSWERBANK_ID,ANSWERBANK_TEXT,ANSWERBANK_EXPLANATION)
VALUES (CSC_ANSWERBANK_SEQUENCE.NEXTVAL,'ans 7v2','short explanation 7');

INSERT INTO CSC_ANSWERBANK(ANSWERBANK_ID,ANSWERBANK_TEXT,ANSWERBANK_EXPLANATION)
VALUES (CSC_ANSWERBANK_SEQUENCE.NEXTVAL,'ans 8v2','short explanation 8');

INSERT INTO CSC_QUESTIONBANK_ANSWERBANK (QABANK_QUESITON_ID,QABANK_ANSWER_ID,QABANK_ISCORRECT)
VALUES (1,1,'T');

INSERT INTO CSC_QUESTIONBANK_ANSWERBANK (QABANK_QUESITON_ID,QABANK_ANSWER_ID,QABANK_ISCORRECT)
VALUES (1,2,'T');

INSERT INTO CSC_QUESTIONBANK_ANSWERBANK (QABANK_QUESITON_ID,QABANK_ANSWER_ID,QABANK_ISCORRECT)
VALUES (1,3,'F');

INSERT INTO CSC_QUESTIONBANK_ANSWERBANK (QABANK_QUESITON_ID,QABANK_ANSWER_ID,QABANK_ISCORRECT)
VALUES (1,4,'F');

INSERT INTO CSC_QUESTIONBANK_ANSWERBANK (QABANK_QUESITON_ID,QABANK_ANSWER_ID,QABANK_ISCORRECT)
VALUES (1,5,'F');

INSERT INTO CSC_QUESTIONBANK_ANSWERBANK (QABANK_QUESITON_ID,QABANK_ANSWER_ID,QABANK_ISCORRECT)
VALUES (1,6,'F');

INSERT INTO CSC_QUESTIONBANK_ANSWERBANK (QABANK_QUESITON_ID,QABANK_ANSWER_ID,QABANK_ISCORRECT)
VALUES (2,1,'T');

INSERT INTO CSC_QUESTIONBANK_ANSWERBANK (QABANK_QUESITON_ID,QABANK_ANSWER_ID,QABANK_ISCORRECT)
VALUES (2,2,'T');

INSERT INTO CSC_QUESTIONBANK_ANSWERBANK (QABANK_QUESITON_ID,QABANK_ANSWER_ID,QABANK_ISCORRECT)
VALUES (2,7,'T');

INSERT INTO CSC_QUESTIONBANK_ANSWERBANK (QABANK_QUESITON_ID,QABANK_ANSWER_ID,QABANK_ISCORRECT)
VALUES (2,4,'F');

INSERT INTO CSC_QUESTIONBANK_ANSWERBANK (QABANK_QUESITON_ID,QABANK_ANSWER_ID,QABANK_ISCORRECT)
VALUES (2,5,'F');

INSERT INTO CSC_QUESTIONBANK_ANSWERBANK (QABANK_QUESITON_ID,QABANK_ANSWER_ID,QABANK_ISCORRECT)
VALUES (2,6,'F');

INSERT INTO CSC_QUESTIONBANK_ANSWERBANK (QABANK_QUESITON_ID,QABANK_ANSWER_ID,QABANK_ISCORRECT)
VALUES (2,8,'F');

INSERT INTO CSC_QUESTIONBANK_ANSWERBANK (QABANK_QUESITON_ID,QABANK_ANSWER_ID,QABANK_ISCORRECT)
VALUES (2,9,'F');

INSERT INTO CSC_QB_VARIABLE(CSC_QB_VARIABLE_SURR_KEY,CSC_QB_VARIABLE_ID,CSC_QB_VAR_Q_ID,CSC_QB_VARIABLE_NAME)
VALUES (CSC_QB_VARIABLE_SEQUENCE.nextval,1,3,'sector size');

INSERT INTO CSC_QB_VARIABLE(CSC_QB_VARIABLE_SURR_KEY,CSC_QB_VARIABLE_ID,CSC_QB_VAR_Q_ID,CSC_QB_VARIABLE_NAME)
VALUES (CSC_QB_VARIABLE_SEQUENCE.nextval,2,3,'tracks per surface');

INSERT INTO CSC_QB_VARIABLE(CSC_QB_VARIABLE_SURR_KEY,CSC_QB_VARIABLE_ID,CSC_QB_VAR_Q_ID,CSC_QB_VARIABLE_NAME)
VALUES (CSC_QB_VARIABLE_SEQUENCE.nextval,3,3,'sectors per track');

INSERT INTO CSC_QB_VARIABLE(CSC_QB_VARIABLE_SURR_KEY,CSC_QB_VARIABLE_ID,CSC_QB_VAR_Q_ID,CSC_QB_VARIABLE_NAME)
VALUES (CSC_QB_VARIABLE_SEQUENCE.nextval,4,3,'double-sided platters');

INSERT INTO CSC_QB_VARIABLE(CSC_QB_VARIABLE_SURR_KEY,CSC_QB_VARIABLE_ID,CSC_QB_VAR_Q_ID,CSC_QB_VARIABLE_NAME)
VALUES (CSC_QB_VARIABLE_SEQUENCE.nextval,5,3,'average seek time');

INSERT INTO CSC_VAR_PARM(CSC_VAR_PARM_SURR_KEY,CSC_VAR_PARM__ID,CSC_VAR_PARM_VAR_SURR_KEY,CSC_VAR_PARM_VALUE)
VALUES (CSC_VAR_PARM_SEQUENCE.nextval,1,1,'512 Bytes');

INSERT INTO CSC_VAR_PARM(CSC_VAR_PARM_SURR_KEY,CSC_VAR_PARM__ID,CSC_VAR_PARM_VAR_SURR_KEY,CSC_VAR_PARM_VALUE)
VALUES (CSC_VAR_PARM_SEQUENCE.nextval,2,1,'256 Bytes');

INSERT INTO CSC_VAR_PARM(CSC_VAR_PARM_SURR_KEY,CSC_VAR_PARM__ID,CSC_VAR_PARM_VAR_SURR_KEY,CSC_VAR_PARM_VALUE)
VALUES (CSC_VAR_PARM_SEQUENCE.nextval,1,2,'2000');

INSERT INTO CSC_VAR_PARM(CSC_VAR_PARM_SURR_KEY,CSC_VAR_PARM__ID,CSC_VAR_PARM_VAR_SURR_KEY,CSC_VAR_PARM_VALUE)
VALUES (CSC_VAR_PARM_SEQUENCE.nextval,2,2,'1000');

INSERT INTO CSC_VAR_PARM(CSC_VAR_PARM_SURR_KEY,CSC_VAR_PARM__ID,CSC_VAR_PARM_VAR_SURR_KEY,CSC_VAR_PARM_VALUE)
VALUES (CSC_VAR_PARM_SEQUENCE.nextval,1,3,'50');

INSERT INTO CSC_VAR_PARM(CSC_VAR_PARM_SURR_KEY,CSC_VAR_PARM__ID,CSC_VAR_PARM_VAR_SURR_KEY,CSC_VAR_PARM_VALUE)
VALUES (CSC_VAR_PARM_SEQUENCE.nextval,2,3,'100');

INSERT INTO CSC_VAR_PARM(CSC_VAR_PARM_SURR_KEY,CSC_VAR_PARM__ID,CSC_VAR_PARM_VAR_SURR_KEY,CSC_VAR_PARM_VALUE)
VALUES (CSC_VAR_PARM_SEQUENCE.nextval,1,4,'5');

INSERT INTO CSC_VAR_PARM(CSC_VAR_PARM_SURR_KEY,CSC_VAR_PARM__ID,CSC_VAR_PARM_VAR_SURR_KEY,CSC_VAR_PARM_VALUE)
VALUES (CSC_VAR_PARM_SEQUENCE.nextval,2,4,'10');

INSERT INTO CSC_VAR_PARM(CSC_VAR_PARM_SURR_KEY,CSC_VAR_PARM__ID,CSC_VAR_PARM_VAR_SURR_KEY,CSC_VAR_PARM_VALUE)
VALUES (CSC_VAR_PARM_SEQUENCE.nextval,1,5,'10 msec');

INSERT INTO CSC_VAR_PARM(CSC_VAR_PARM_SURR_KEY,CSC_VAR_PARM__ID,CSC_VAR_PARM_VAR_SURR_KEY,CSC_VAR_PARM_VALUE)
VALUES (CSC_VAR_PARM_SEQUENCE.nextval,2,5,'20 msec');

INSERT INTO CSC_QB_PARAMETER_SET(CSC_QB_PARAMETER_SET_ID,CSC_QB_PARAMETER_SET_PARM_ID)
VALUES(1,1);

INSERT INTO CSC_QB_PARAMETER_SET(CSC_QB_PARAMETER_SET_ID,CSC_QB_PARAMETER_SET_PARM_ID)
VALUES(1,3);

INSERT INTO CSC_QB_PARAMETER_SET(CSC_QB_PARAMETER_SET_ID,CSC_QB_PARAMETER_SET_PARM_ID)
VALUES(1,5);

INSERT INTO CSC_QB_PARAMETER_SET(CSC_QB_PARAMETER_SET_ID,CSC_QB_PARAMETER_SET_PARM_ID)
VALUES(1,7);

INSERT INTO CSC_QB_PARAMETER_SET(CSC_QB_PARAMETER_SET_ID,CSC_QB_PARAMETER_SET_PARM_ID)
VALUES(1,9);

INSERT INTO CSC_QB_PARAMETER_SET(CSC_QB_PARAMETER_SET_ID,CSC_QB_PARAMETER_SET_PARM_ID)
VALUES(2,2);

INSERT INTO CSC_QB_PARAMETER_SET(CSC_QB_PARAMETER_SET_ID,CSC_QB_PARAMETER_SET_PARM_ID)
VALUES(2,4);

INSERT INTO CSC_QB_PARAMETER_SET(CSC_QB_PARAMETER_SET_ID,CSC_QB_PARAMETER_SET_PARM_ID)
VALUES(2,6);

INSERT INTO CSC_QB_PARAMETER_SET(CSC_QB_PARAMETER_SET_ID,CSC_QB_PARAMETER_SET_PARM_ID)
VALUES(2,8);

INSERT INTO CSC_QB_PARAMETER_SET(CSC_QB_PARAMETER_SET_ID,CSC_QB_PARAMETER_SET_PARM_ID)
VALUES(2,10);

INSERT INTO CSC_QB_AB_PARM(CSC_QBANK_ANSBANK_PARM_SET_ID,CSC_QB_AB_PARM_ANSWER_ID,CSC_QB_AB_PARM_ISCORRECT)
VALUES(1,10,'T');

INSERT INTO CSC_QB_AB_PARM(CSC_QBANK_ANSBANK_PARM_SET_ID,CSC_QB_AB_PARM_ANSWER_ID,CSC_QB_AB_PARM_ISCORRECT)
VALUES(1,11,'T');

INSERT INTO CSC_QB_AB_PARM(CSC_QBANK_ANSBANK_PARM_SET_ID,CSC_QB_AB_PARM_ANSWER_ID,CSC_QB_AB_PARM_ISCORRECT)
VALUES(1,12,'T');

INSERT INTO CSC_QB_AB_PARM(CSC_QBANK_ANSBANK_PARM_SET_ID,CSC_QB_AB_PARM_ANSWER_ID,CSC_QB_AB_PARM_ISCORRECT)
VALUES(1,13,'F');

INSERT INTO CSC_QB_AB_PARM(CSC_QBANK_ANSBANK_PARM_SET_ID,CSC_QB_AB_PARM_ANSWER_ID,CSC_QB_AB_PARM_ISCORRECT)
VALUES(1,14,'F');

INSERT INTO CSC_QB_AB_PARM(CSC_QBANK_ANSBANK_PARM_SET_ID,CSC_QB_AB_PARM_ANSWER_ID,CSC_QB_AB_PARM_ISCORRECT)
VALUES(1,15,'F');

INSERT INTO CSC_QB_AB_PARM(CSC_QBANK_ANSBANK_PARM_SET_ID,CSC_QB_AB_PARM_ANSWER_ID,CSC_QB_AB_PARM_ISCORRECT)
VALUES(1,16,'F');

INSERT INTO CSC_QB_AB_PARM(CSC_QBANK_ANSBANK_PARM_SET_ID,CSC_QB_AB_PARM_ANSWER_ID,CSC_QB_AB_PARM_ISCORRECT)
VALUES(1,17,'F');

INSERT INTO CSC_QB_AB_PARM(CSC_QBANK_ANSBANK_PARM_SET_ID,CSC_QB_AB_PARM_ANSWER_ID,CSC_QB_AB_PARM_ISCORRECT)
VALUES(2,18,'T');

INSERT INTO CSC_QB_AB_PARM(CSC_QBANK_ANSBANK_PARM_SET_ID,CSC_QB_AB_PARM_ANSWER_ID,CSC_QB_AB_PARM_ISCORRECT)
VALUES(2,19,'T');

INSERT INTO CSC_QB_AB_PARM(CSC_QBANK_ANSBANK_PARM_SET_ID,CSC_QB_AB_PARM_ANSWER_ID,CSC_QB_AB_PARM_ISCORRECT)
VALUES(2,20,'T');

INSERT INTO CSC_QB_AB_PARM(CSC_QBANK_ANSBANK_PARM_SET_ID,CSC_QB_AB_PARM_ANSWER_ID,CSC_QB_AB_PARM_ISCORRECT)
VALUES(2,21,'F');

INSERT INTO CSC_QB_AB_PARM(CSC_QBANK_ANSBANK_PARM_SET_ID,CSC_QB_AB_PARM_ANSWER_ID,CSC_QB_AB_PARM_ISCORRECT)
VALUES(2,22,'F');

INSERT INTO CSC_QB_AB_PARM(CSC_QBANK_ANSBANK_PARM_SET_ID,CSC_QB_AB_PARM_ANSWER_ID,CSC_QB_AB_PARM_ISCORRECT)
VALUES(2,23,'F');

INSERT INTO CSC_QB_AB_PARM(CSC_QBANK_ANSBANK_PARM_SET_ID,CSC_QB_AB_PARM_ANSWER_ID,CSC_QB_AB_PARM_ISCORRECT)
VALUES(2,24,'F');

INSERT INTO CSC_QB_AB_PARM(CSC_QBANK_ANSBANK_PARM_SET_ID,CSC_QB_AB_PARM_ANSWER_ID,CSC_QB_AB_PARM_ISCORRECT)
VALUES(2,25,'F');

INSERT INTO CSC_EXERCISE_QUESTION(EA_ID,EA_EXERCISE_ID,EA_QUESTION_ID,EA_QUES_IS_PARM)
VALUES (CSC_EXERCISE_QUESTION_SEQUENCE.nextval,1,1,'F');

INSERT INTO CSC_EXERCISE_QUESTION(EA_ID,EA_EXERCISE_ID,EA_QUESTION_ID,EA_QUES_IS_PARM)
VALUES (CSC_EXERCISE_QUESTION_SEQUENCE.nextval,1,2,'F');

INSERT INTO CSC_EXERCISE_QUESTION(EA_ID,EA_EXERCISE_ID,EA_QUESTION_ID,EA_QUES_IS_PARM)
VALUES (CSC_EXERCISE_QUESTION_SEQUENCE.nextval,1,1,'T');
