/**
 * 
 */
package ncsu.dbms.core;

/**
 * @author ravi
 *
 */
public class QuestionBank_Topic {
	int QT_TOPIC_ID =0;
	int QT_QUESTIONBANK_ID=0;
}
/**
 * 
CREATE TABLE CSC_EXERCISE_QUESTION
(
EA_ID INTEGER NOT NULL,
EA_EXERCISE_ID INTEGER NOT NULL,
EA_QUESTION_ID INTEGER NOT NULL,
CONSTRAINT EA_EXERCISE_ID_FK FOREIGN KEY (EA_EXERCISE_ID) REFERENCES  CSC_EXERCISE(EXERCISE_ID),
CONSTRAINT EA_QUESTION_ID_FK FOREIGN KEY (EA_QUESTION_ID) REFERENCES CSC_QUESTIONBANK(QUESTIONBANK_ID)
);
CREATE SEQUENCE CSC_EXERCISE_QUESTION_SEQUENCE
MINVALUE 1
START WITH 1
INCREMENT BY 1;

CREATE TABLE CSC_USER_ATTEMPT
(
UA_ID INTEGER NOT NULL,
UA_USER_ID INTEGER NOT NULL,
UA_EXERCISE_ID INTEGER NOT NULL,
UA_STARTATTEMPT_DATE varchar(25),
UA_LASTATTEMPT_DATE varchar(25),
UA_SUBMITTED CHAR(1) DEFAULT('F'),
UA_SCORE DECIMAL(18,2) DEFAULT(0.00),
CONSTRAINT CSC_USER_ATTEMPT_ID_PK PRIMARY KEY(UA_ID),
CONSTRAINT CSC_USER_ATTEMPT_EXERCISE_ID FOREIGN KEY(UA_EXERCISE_ID) REFERENCES CSC_EXERCISE(EXERCISE_ID)
);

CREATE SEQUENCE CSC_USER_ATTEMPT_SEQUENCE
MINVALUE 1
START WITH 1
INCREMENT BY 1;


CREATE TABLE CSC_USERATTEMPT_EXERCISE
(
UE_UA_ID INTEGER NOT NULL,
UE_QUESTION_ID INTEGER NOT NULL,
UE_ANSWER_ID INTEGER NOT NULL,
UE_ISSELECTED CHAR(1) DEFAULT ('F'),
CONSTRAINT CSC_UE_UK UNIQUE(UE_UA_ID,UE_QUESTION_ID, UE_ANSWER_ID),
CONSTRAINT CSC_UE_UA_ID_FK FOREIGN KEY (UE_UA_ID) REFERENCES CSC_USER_ATTEMPT (UA_ID),
CONSTRAINT CSC_UE_QUESTION_ID_FK FOREIGN KEY (UE_QUESTION_ID) REFERENCES CSC_QUESTIONBANK (QUESTIONBANK_ID),
CONSTRAINT CSC_UE_ANSWER_ID_FK FOREIGN KEY (UE_ANSWER_ID) REFERENCES CSC_ANSWERBANK (ANSWERBANK_ID)
);

ALTER TABLE csc_user
modify( USER_CREATEDDATE varchar(25));
ALTER TABLE csc_user
modify( USER_LASTMODIFIEDDATE varchar(25));

ALTER TABLE CSC_COURSE
add (CSC_COURSE_Course_ID_char varchar(25));


ALTER TABLE CSC_COURSE
add (CSC_COURSE_token varchar(25));

CREATE TABLE CSC_LEVEL_STUDENT
(
CSC_LEVEL_STUDENT_LEVEL_ID INTEGER,
CSC_LEVEL_LEVEL_TYPE VARCHAR(200),
CONSTRAINT CSC_LEVEL_STUDENT_pk primary key (CSC_LEVEL_STUDENT_LEVEL_ID)
);

CREATE SEQUENCE CSC_LEVEL_STUDENT_SEQUENCE
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 10;

alter table csc_user
add (user_id_char varchar(25));

alter table csc_user
add (Constraint csc_user_unq unique(user_id_char) );

CREATE SEQUENCE CSC_USER_ROLE_SEQUENCE 
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 10;


CREATE TABLE CSC_LEVEL_STUDENT_USER
(
CSC_LEVEL_STU_USER_SURR_KEY INTEGER,
CSC_LEVEL_STU_USER_LEVEL_ID integer,
CSC_LEVEL_STU_USER_USER_ID integer,
CONSTRAINT CSC_STUDENT_LEVEL_pk primary key (CSC_LEVEL_STU_USER_SURR_KEY),
CONSTRAINT CSC_STUDENT_LEVEL_UNQ UNIQUE (CSC_LEVEL_STU_USER_LEVEL_ID,CSC_LEVEL_STU_USER_USER_ID),
CONSTRAINT CSC_STUDENT_LEVEL_FK1 FOREIGN KEY (CSC_LEVEL_STU_USER_USER_ID) REFERENCES CSC_USER(USER_ID ),
CONSTRAINT CSC_STUDENT_LEVEL_FK2 FOREIGN KEY (CSC_LEVEL_STU_USER_LEVEL_ID) REFERENCES CSC_LEVEL_STUDENT(CSC_LEVEL_STUDENT_LEVEL_ID )
);
CREATE SEQUENCE CSC_LEVEL_STUDENT_USER
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 10;


/
 */